Very minor change in alimeeting recipe
No need to load_audio. alimeeting audio data is wav format, default export_to_webdataset uses "flac".  If load_audio uses default (True), webdataset would show "[Suppressed TypeError] Error message: save() got an unexpected keyword argument 'format'" during write