Update decode.py (#392)
* Update decode.py

fix bug ```TypeError: greedy_search_batch() missing 1 required positional argument: 'encoder_out_lens'```

* fix modified_beam_search

Co-authored-by: fanlu3 <fanlu@jd.com>